name = "studyops-server"
main = "src/index.ts"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "studyops-db"
database_id = "a0459919-418c-4563-bf8b-162eeff0396e"
migrations_dir = "src/db/migrations"

[vars]
TOSS_AUTH_MODE = "dev"
TOSS_API_BASE_URL = "https://apps-in-toss-api.toss.im"
