// Astro v5 Content Layer API를 사용한 콘텐츠 컬렉션 스키마.
// HARNESS.md §5 (산출물 규약)의 frontmatter 규약과 1:1 대응.
// 스키마 변경 시 반드시 HARNESS.md도 함께 업데이트.
import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

// ─── 공통: 날짜/타임스탬프 ───────────────────────────────────────────────────
// YAML frontmatter의 날짜는 Astro가 자동으로 Date 객체로 파싱한다.
// 문자열("2026-07-26")과 Date 객체를 모두 받아들이도록 coerce.
const isoTimestamp = z.coerce.date();

// ─── 1. episodes — 작업 단위 (한 번의 sprint / 이슈 해결 = 한 에피소드) ───────
const episodes = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/episodes' }),
  schema: z.object({
    // 필수
    id: z.string(),
    title: z.string(),
    type: z.enum(['feature', 'bug', 'refactor', 'docs', 'infra', 'qa']),
    status: z.enum(['planned', 'in-progress', 'review', 'shipped', 'cancelled']),
    startedAt: isoTimestamp,
    // 옵셔널
    shippedAt: isoTimestamp.nullable().default(null),
    sessionIds: z.array(z.string()).default([]),
    relatedDecisions: z.array(z.string()).default([]),
    touchedFiles: z.array(z.string()).default([]),
    linearIssue: z.string().nullable().default(null),
    githubPR: z.string().nullable().default(null),
    tags: z.array(z.string()).default([]),
    summary: z.string().default(''),
  }),
});
// ─── 2. decisions — ADR (Architecture Decision Records) ──────────────────────
const decisions = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/decisions' }),
  schema: z.object({
    id: z.string(),                              // adr-001, adr-002...
    title: z.string(),
    status: z.enum([
      'proposed',                                // 제안됨
      'accepted',                                // 채택됨
      'deprecated',                              // 사용 중단
      'superseded',                              // 다른 ADR로 대체됨
      'rejected',                                // 기각됨
    ]),
    date: isoTimestamp,
    // supersededBy는 status가 superseded일 때만 의미. schema 수준에서 의존성 검사는 별도.
    supersededBy: z.string().nullable().default(null),
    tags: z.array(z.string()).default([]),
  }),
});

// ─── 3. qa — QA 세션 (UI 변경 검증) ──────────────────────────────────────────
// 한 에피소드 안에서 여러 QA 세션이 발생할 수 있음. 1:1이 아닌 다:1.
const qa = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/qa' }),
  schema: z.object({
    id: z.string(),
    target: z.string(),                          // 검증 대상 ("login-page", "round-detail-status" 등)
    date: isoTimestamp,
    result: z.enum(['pass', 'fail', 'partial', 'blocked']),
    // 상대경로 (public 기준). 예: "/qa/2026-07-15-login/01-login.png"
    screenshots: z.array(z.object({
      path: z.string(),
      label: z.string().default(''),
    })).default([]),
    episodeId: z.string().nullable().default(null),
    notes: z.string().default(''),
    environment: z.string().default(''),         // "local", "preview", "prod"
    browser: z.string().default(''),             // "Chrome 126", "WebView" 등
  }),
});

// ─── 4. sessions — .omo 세션 자동 인덱스 (자동 생성, 수동 편집 금지) ───────────
// scripts/index-local.ts 가 .omo/run-continuation/*.json 을 읽어서 이 디렉토리에 쓴다.
const sessions = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/sessions' }),
  schema: z.object({
    sessionId: z.string(),                       // ses_xxx
    updatedAt: isoTimestamp,
    // OpenCode 저장소에서 파싱한 추가 메타데이터 (있을 경우)
    agent: z.string().default('unknown'),
    messageCount: z.number().int().nonnegative().default(0),
    duration: z.number().nonnegative().default(0), // seconds
    firstMessageAt: isoTimestamp.nullable().default(null),
    lastMessageAt: isoTimestamp.nullable().default(null),
    relatedEpisodes: z.array(z.string()).default([]),
    autoGenerated: z.boolean().default(true),    // 수동 편집 금지 플래그
  }),
});

// ─── 5. changelog — 외부 연동 캐시 (Phase 2: Linear, GitHub PR, Discord) ──────
// 현재는 빈 컬렉션. Phase 2에서 fetch 스크립트가 채움.
const changelog = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/changelog' }),
  schema: z.object({
    id: z.string(),
    source: z.enum(['linear', 'github', 'discord', 'manual']),
    externalId: z.string(),                      // Linear issue key, PR number, Discord message ID
    title: z.string(),
    timestamp: isoTimestamp,
    url: z.string().url().nullable().default(null),
    author: z.string().default(''),
    autoGenerated: z.boolean().default(true),
    relatedEpisodes: z.array(z.string()).default([]),
  }),
});

export const collections = { episodes, decisions, qa, sessions, changelog };
