/**
 * 로컬 작업 데이터를 위키 콘텐츠로 인덱싱.
 *
 * 입력:
 *   - ../../.omo/run-continuation/*.json   → sessions/ 컬렉션
 *   - ../../qa-*.png, ../../screen-*.png    → public/qa/legacy/ 복사 + qa/ 컬렉션 메타데이터
 *
 * 출력 (모두 멱등 — 재실행해도 안전):
 *   - src/content/sessions/ses-<id>.md
 *   - public/qa/legacy/<filename>
 *   - src/content/qa/<auto>-legacy-<n>.md  (메타데이터만, 파일 자체는 복사본)
 *
 * Phase 2에서 Linear/GitHub/Discord 연동이 추가되면 별도 스크립트로 확장.
 *
 * 사용: npm run index  (docs/wiki/ 안에서)
 */
import { readdir, readFile, writeFile, mkdir, copyFile, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const WIKI_ROOT = resolve(__dirname, '..');
const REPO_ROOT = resolve(WIKI_ROOT, '..', '..');

const SESSIONS_SRC = join(REPO_ROOT, '.omo', 'run-continuation');
const SESSIONS_DST = join(WIKI_ROOT, 'src', 'content', 'sessions');

const QA_LEGACY_PATTERNS = [/^qa-.*\.png$/i, /^screen-.*\.png$/i];
const QA_PUBLIC_DST = join(WIKI_ROOT, 'public', 'qa', 'legacy');
const QA_COLLECTION_DST = join(WIKI_ROOT, 'src', 'content', 'qa');

// ─── 유틸리티 ────────────────────────────────────────────────────────────────
function escapeYaml(value: string): string {
  // 단순 문자열은 그대로, 특수문자 포함 시 따옴표.
  if (/^[\w\s가-힣.,:/@-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

function toIsoString(ms: number): string {
  return new Date(ms).toISOString();
}

// ─── 1. 세션 인덱싱 ──────────────────────────────────────────────────────────
interface SessionState {
  sessionID: string;
  updatedAt?: string;
  sources?: Record<string, { state: string; updatedAt: string }>;
}

async function indexSessions(): Promise<{ indexed: number; skipped: number }> {
  if (!existsSync(SESSIONS_SRC)) {
    console.warn(`  ⚠ 세션 소스 디렉토리 없음: ${SESSIONS_SRC}`);
    return { indexed: 0, skipped: 0 };
  }

  await mkdir(SESSIONS_DST, { recursive: true });

  const files = (await readdir(SESSIONS_SRC)).filter((f) => f.endsWith('.json'));
  let indexed = 0;
  let skipped = 0;

  for (const file of files) {
    const srcPath = join(SESSIONS_SRC, file);
    const raw = await readFile(srcPath, 'utf8');
    let data: SessionState;
    try {
      data = JSON.parse(raw) as SessionState;
    } catch {
      console.warn(`  ⚠ 파싱 실패 (건너뜀): ${file}`);
      skipped++;
      continue;
    }

    if (!data.sessionID) {
      console.warn(`  ⚠ sessionID 없음 (건너뜀): ${file}`);
      skipped++;
      continue;
    }

    const safeId = data.sessionID.replace(/[^A-Za-z0-9_-]/g, '_');
    const dstPath = join(SESSIONS_DST, `${safeId}.md`);
    const updatedAt = data.updatedAt ?? new Date().toISOString();

    // 어떤 source 들이 활성화되어 있었는지 요약
    const sourceSummary = data.sources
      ? Object.entries(data.sources)
          .map(([k, v]) => `${k}:${v.state}`)
          .join(', ')
      : 'none';

    const frontmatter = [
      '---',
      `sessionId: ${escapeYaml(data.sessionID)}`,
      `updatedAt: ${updatedAt}`,
      `agent: sisyphus`,
      `messageCount: 0`,
      `duration: 0`,
      `firstMessageAt: null`,
      `lastMessageAt: ${updatedAt}`,
      `relatedEpisodes: []`,
      `autoGenerated: true`,
      '---',
      '',
      `# Session ${data.sessionID}`,
      '',
      `> 자동 생성됨. 수동 편집 금지. (스크립트: \`scripts/index-local.ts\`)`,
      '',
      `**마지막 업데이트**: ${updatedAt}`,
      '',
      `**소스 상태**: ${sourceSummary}`,
      '',
      `**원본**: \`../../.omo/run-continuation/${file}\``,
      '',
      '## 메모',
      '',
      '(Phase 2: opencode.db 에서 메시지 히스토리 파싱)',
      '',
    ].join('\n');

    await writeFile(dstPath, frontmatter, 'utf8');
    indexed++;
  }

  return { indexed, skipped };
}

// ─── 2. 레거시 QA 스크린샷 인덱싱 ────────────────────────────────────────────
interface LegacyScreenshot {
  file: string;
  size: number;
  mtime: number;
}

async function indexLegacyQa(): Promise<{ copied: number; indexed: number }> {
  // 루트에 흩어진 qa-*.png, screen-*.png 찾기
  const rootFiles = await readdir(REPO_ROOT);
  const legacyPngs: LegacyScreenshot[] = [];

  for (const file of rootFiles) {
    if (!QA_LEGACY_PATTERNS.some((p) => p.test(file))) continue;
    const fullPath = join(REPO_ROOT, file);
    const st = await stat(fullPath);
    if (!st.isFile()) continue;
    legacyPngs.push({ file, size: st.size, mtime: st.mtimeMs });
  }

  if (legacyPngs.length === 0) {
    console.warn(`  ℹ 레거시 QA 스크린샷 없음`);
    return { copied: 0, indexed: 0 };
  }

  await mkdir(QA_PUBLIC_DST, { recursive: true });
  await mkdir(QA_COLLECTION_DST, { recursive: true });

  // 파일 복사 (public/qa/legacy/)
  for (const item of legacyPngs) {
    const src = join(REPO_ROOT, item.file);
    const dst = join(QA_PUBLIC_DST, item.file);
    await copyFile(src, dst);
  }

  // 하나의 메타데이터 마크다운으로 묶기 (레거시는 한 에피소드로 처리)
  // 7/15 MVP 1차 QA 세션으로 가정 (수정 필요하면 위키에서 직접 편집)
  const sorted = [...legacyPngs].sort((a, b) => a.file.localeCompare(b.file));
  const date = sorted[0] ? toIsoString(sorted[0].mtime) : '2026-07-15';

  const screenshotsYaml = sorted
    .map((s) => `  - path: /qa/legacy/${s.file}\n    label: ${escapeYaml(s.file.replace(/\.(png|jpg|jpeg)$/i, ''))}`)
    .join('\n');

  const totalKb = (sorted.reduce((a, b) => a + b.size, 0) / 1024).toFixed(1);
  const md = [
    '---',
    `id: 2026-07-15-mvp1-qa-legacy`,
    `target: mvp-1-screens`,
    `date: ${date}`,
    `result: pass`,
    `screenshots:`,
    screenshotsYaml,
    `episodeId: 2026-07-12-mvp-1-sprint`,
    `notes: "MVP 1차 sprint 종료 후 Playwright MCP로 캡처한 8개 화면 + 화면 설계안 2개. 원래 루트에 흩어져 있던 파일을 자동 수집."`,
    `environment: local`,
    `browser: playwright-chromium`,
    '---',
    '',
    '# MVP 1차 QA (Legacy)',
    '',
    '> 자동 생성됨. `index-local.ts` 스크립트가 루트의 qa-*.png, screen-*.png 파일들을 수집하여 구조화.',
    '> 향후 새 QA 세션은 `docs/wiki/src/content/qa/`에 직접 작성.',
    '',
    '## 검증 항목',
    '',
    sorted
      .map((s) => `- ![${s.file}](/qa/legacy/${s.file}) — ${s.file}`)
      .join('\n'),
    '',
    '## 원본 위치',
    '',
    `- 파일: 루트의 qa-*.png, screen-*.png`,
    `- 크기 합계: ${totalKb} KB`,
    '',
  ].join('\n');

  const collectionPath = join(QA_COLLECTION_DST, '2026-07-15-mvp1-qa-legacy.md');
  await writeFile(collectionPath, md, 'utf8');

  return { copied: legacyPngs.length, indexed: 1 };
}

// ─── 메인 ────────────────────────────────────────────────────────────────────
async function main(): Promise<void> {
  console.log('📚 StudyOps Wiki — 로컬 데이터 인덱싱 시작');
  console.log(`   REPO_ROOT: ${REPO_ROOT}`);
  console.log('');

  console.log('1️⃣  .omo 세션 인덱싱...');
  const sessions = await indexSessions();
  console.log(`   ✅ ${sessions.indexed}개 색인, ${sessions.skipped}개 스킵`);

  console.log('2️⃣  레거시 QA 스크린샷 수집...');
  const qa = await indexLegacyQa();
  console.log(`   ✅ ${qa.copied}개 파일 복사, ${qa.indexed}개 메타데이터 생성`);

  console.log('');
  console.log('✨ 완료. `npm run dev` 로 위키를 확인하세요.');
}

main().catch((err) => {
  console.error('❌ 인덱싱 실패:', err);
  process.exit(1);
});
